### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Chandan-devs-tech** [Mikey1-nuel/Setup-and-Mobile-First#9]
Hi @Mikey1-nuel,
- Great job is done by you so far.
- You need some changes done in the responsiveness of the portfolio.
# Changes Required ♻️ 
- Please remove the width from every section so it makes your portfolio responsive to every device.
<img width="513" alt="emma" src="https://user-images.githubusercontent.com/65088027/224249256-b9fcf087-8eb5-4cc0-92a6-ab7f8f3a3199.png">
<img src="https://media4.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

**Comment by helina42** [comment]
@Mikey1-nuel  hi,

Good job so far! 👏👏👏
There are some issues that you still need to work on but you are almost there! 😃

![giphy (1)](https://user-images.githubusercontent.com/112048040/224250925-842657ab-959a-4176-b8be-fda1c0625616.gif)

When opening the desktop version there seems to be an extra white space, Please consider removing it by changing the widths from px to % or find if there is an overflow in one of your content.

**Comment by Mikey1-nuel** [comment]
Issue rectified
